using Api.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Api.Common.Persistence.Configurations;

public class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> builder)
    {
        builder.ToTable("users");

        builder.HasKey(x => x.Id);

        builder.Property(x => x.Id)
            .ValueGeneratedNever(); // Generated by IdFactory.

        builder.Property(x => x.Email)
            .IsRequired()
            .HasMaxLength(320);

        // Email is normalized to lower-case before persisting, so a plain
        // unique index enforces case-insensitive uniqueness.
        builder.HasIndex(x => x.Email).IsUnique();

        builder.Property(x => x.PasswordHash)
            .IsRequired();

        builder.Property(x => x.Name)
            .IsRequired()
            .HasMaxLength(100);

        builder.Property(x => x.Avatar)
            .HasMaxLength(2048);

        builder.Property(x => x.CreatedAt)
            .IsRequired();
    }
}
