namespace Api.Domain;

/// <summary>
/// A registered account. Authenticates via email + password; no OAuth.
/// </summary>
public class User
{
    /// <summary>Primary key — generated by <c>IdFactory</c>, never by the database.</summary>
    public long Id { get; set; }

    /// <summary>Login identifier. Unique, stored lower-case.</summary>
    public required string Email { get; set; }

    /// <summary>Argon2id encoded hash (salt and parameters embedded).</summary>
    public required string PasswordHash { get; set; }

    /// <summary>Display name.</summary>
    public required string Name { get; set; }

    /// <summary>Optional avatar URL. Not set during the Auth feature.</summary>
    public string? Avatar { get; set; }

    /// <summary>Creation timestamp, UTC.</summary>
    public DateTime CreatedAt { get; set; }
}
